module.exports = [ "50 Y Free",
                   "100 Y Free",
                   "200 Y Free",
                   "500 Y Free",
                   "1000 Y Free",
                   "1650 Y Free",
                   "100 Y Back",
                   "200 Y Back",
                   "100 Y Breast",
                   "200 Y Breast",
                   "100 Y Fly",
                   "200 Y Fly",
                   "100 Y IM",
                   "200 Y IM",
                   "400 Y IM" ];
